---
AllCops:
  TargetRubyVersion: 3.4

Style/Documentation:
  Enabled: false

Metrics/ClassLength:
  Max: 200

Metrics/MethodLength:
  Max: 40

Metrics/AbcSize:
  Max: 30

Metrics/CyclomaticComplexity:
  Max: 10
